name: build image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout code
        uses: actions/checkout@v2
      -
        name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      -
        name: set up qemu
        uses: docker/setup-qemu-action@v1
      -
        name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      -
        name: build the image
        run: |
          VERSION=$(cat VERSION)
          docker buildx build --push \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --tag jovalle/qbittorrent-openvpn:${VERSION} .